/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.13
 * Generated at: 2021-11-24 09:23:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.lib.mgt.controller.LoginCtl;
import in.co.lib.mgt.controller.LIBView;
import in.co.lib.mgt.bean.UserBean;

public final class WelcomeView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/Footer.jsp", Long.valueOf(1637735981631L));
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1637735981707L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("in.co.lib.mgt.bean.UserBean");
    _jspx_imports_classes.add("in.co.lib.mgt.controller.LoginCtl");
    _jspx_imports_classes.add("in.co.lib.mgt.controller.LIBView");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Welcome</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write(" <!-- Bootstrap CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/css/bootstrap.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/vendors/linericon/style.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/css/font-awesome.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/vendors/lightbox/simpleLightbox.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/vendors/nice-select/css/nice-select.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/vendors/animate-css/animate.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/vendors/popup/magnific-popup.css\">\r\n");
      out.write("        <!-- main css -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/css/style.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/css/responsive.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/css/login.css\">\r\n");
      out.write("        \r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	UserBean userDto = (UserBean) session.getAttribute("user");

	boolean userLoggedIn = userDto != null;

	String welcomeMsg = "Hi, ";

	if (userLoggedIn) {
		welcomeMsg += userDto.getFirstName().toUpperCase();
	} else {
		welcomeMsg += "Guest";
	}

      out.write("\r\n");
      out.write("       <header class=\"header_area\">\r\n");
      out.write("          \t\r\n");
      out.write("            <div class=\"main_menu\">\r\n");
      out.write("            \t<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t\t\t\t<a class=\"navbar-brand logo_h\" href=\"index.html\">Library Management</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"collapse navbar-collapse offset\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav navbar-nav menu_nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\" href=\"");
      out.print(LIBView.WELCOME_CTL);
      out.write("\">Home</a></li>\r\n");
      out.write("\t\t\t\t");

				if (userLoggedIn) {
				
      out.write(" \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
if(userDto.getRoleId()==1){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(LIBView.USER_LIST_CTL);
      out.write("\">User</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item submenu dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Book Dashbord</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(LIBView.BOOK_CTL);
      out.write("\">Add Book</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(LIBView.BOOK_LIST_CTL);
      out.write("\">Books</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item submenu dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Issue Book</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(LIBView.ISSU_BOOK_CTL);
      out.write("\">Issue Book </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(LIBView.ISSU_BOOK_LIST_CTL);
      out.write("\">Issue Book Report</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(LIBView.CHANGE_PASSWORD_CTL);
      out.write("\">Change Password</a></li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
}
				if(userDto.getRoleId()==2){
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(LIBView.USER_CTL);
      out.write("\">My Profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(LIBView.ISSU_BOOK_LIST_CTL);
      out.write("\">Issue Book</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(LIBView.CHANGE_PASSWORD_CTL);
      out.write("\">Change Password</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
}} 
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t");

 					if (userLoggedIn) {
						 
      out.write("\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(LIBView.LOGIN_CTL);
      out.write("?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
}else{ 
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(LIBView.LOGIN_CTL);
      out.write("\">Login</a></li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(LIBView.USER_REGISTRATION_CTL);
      out.write("\">SignUp</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("            \t</nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\t<h2 style=\"margin: 240px; font-family: inherit;\"  >Welcome To Library Management System</h2>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/StudentInformationSystem/css/bootstrap.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/vendors/linericon/style.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/css/font-awesome.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/vendors/lightbox/simpleLightbox.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/vendors/nice-select/css/nice-select.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/vendors/animate-css/animate.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/vendors/popup/magnific-popup.css\">\r\n");
      out.write("        <!-- main css -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/css/style.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/LibraryMgt/css/responsive.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <!--================ start footer Area  =================-->\t\r\n");
      out.write("        <footer class=\"footer-area p_120\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-2  col-md-6 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("                           <h6 class=\"footer_title\">Top Products</h6>\r\n");
      out.write("                            <ul class=\"list\">\r\n");
      out.write("                            \t<li><a href=\"#\">Managed Website</a></li>\r\n");
      out.write("                            \t<li><a href=\"#\">Manage Reputation</a></li>\r\n");
      out.write("                            \t<li><a href=\"#\">Power Tools</a></li>\r\n");
      out.write("                            \t<li><a href=\"#\">Marketing Service</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-2  col-md-6 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("                           <h6 class=\"footer_title\">Quick Links</h6>\r\n");
      out.write("                            <ul class=\"list\">\r\n");
      out.write("                            \t<li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("                            \t<li><a href=\"#\">Brand Assets</a></li>\r\n");
      out.write("                            \t<li><a href=\"#\">Investor Relations</a></li>\r\n");
      out.write("                            \t<li><a href=\"#\">Terms of Service</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-2  col-md-6 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("                           <h6 class=\"footer_title\">Features</h6>\r\n");
      out.write("                            <ul class=\"list\">\r\n");
      out.write("                            \t<li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("                            \t<li><a href=\"#\">Brand Assets</a></li>\r\n");
      out.write("                            \t<li><a href=\"#\">Investor Relations</a></li>\r\n");
      out.write("                            \t<li><a href=\"#\">Terms of Service</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-2  col-md-6 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("                           <h6 class=\"footer_title\">Resources</h6>\r\n");
      out.write("                            <ul class=\"list\">\r\n");
      out.write("                            \t<li><a href=\"#\">Guides</a></li>\r\n");
      out.write("                            \t<li><a href=\"#\">Research</a></li>\r\n");
      out.write("                            \t<li><a href=\"#\">Experts</a></li>\r\n");
      out.write("                            \t<li><a href=\"#\">Agencies</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("                        <aside class=\"f_widget news_widget\">\r\n");
      out.write("        \t\t\t\t\t<div class=\"f_title\">\r\n");
      out.write("        \t\t\t\t\t\t<h3 class=\"footer_title\">Newsletter</h3>\r\n");
      out.write("        \t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\t<p>Stay updated with our latest trends</p>\r\n");
      out.write("        \t\t\t\t\t<div id=\"mc_embed_signup\">\r\n");
      out.write("                                <form target=\"_blank\" action=\"https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01\" method=\"get\" class=\"subscribe_form relative\">\r\n");
      out.write("                                \t<div class=\"input-group d-flex flex-row\">\r\n");
      out.write("                                        <input name=\"EMAIL\" placeholder=\"Enter email address\" onfocus=\"this.placeholder = ''\" onblur=\"this.placeholder = 'Email Address '\" required=\"\" type=\"email\">\r\n");
      out.write("                                        <button class=\"btn sub-btn\"><span class=\"lnr lnr-arrow-right\"></span></button>\t\t\r\n");
      out.write("                                    </div>\t\t\t\t\r\n");
      out.write("                                    <div class=\"mt-10 info\"></div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("        \t\t\t\t</aside>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row footer-bottom d-flex justify-content-between align-items-center\">\r\n");
      out.write("                    <p class=\"col-lg-8 col-md-8 footer-text m-0\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-4 footer-social\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-behance\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\t\t<!--================ End footer Area  =================-->\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- Optional JavaScript -->\r\n");
      out.write("        <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("     <!--    <script src=\"/LibraryMgt/js/jquery-3.3.1.min.js\"></script> -->\r\n");
      out.write("<!--         <script src=\"/LibraryMgt/js/popper.js\"></script> -->\r\n");
      out.write("    <!--     <script src=\"/LibraryMgt/js/bootstrap.min.js\"></script> -->\r\n");
      out.write("     <!--    <script src=\"/LibraryMgt/js/stellar.js\"></script>\r\n");
      out.write("        <script src=\"/LibraryMgt/vendors/lightbox/simpleLightbox.min.js\"></script>\r\n");
      out.write("        <script src=\"/LibraryMgt/vendors/nice-select/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("        <script src=\"/LibraryMgt/vendors/isotope/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("        <script src=\"/LibraryMgt/vendors/isotope/isotope.pkgd.min.js\"></script>\r\n");
      out.write("        <script src=\"/LibraryMgt/vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("        <script src=\"/LibraryMgt/vendors/popup/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("        <script src=\"/LibraryMgt/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("        <script src=\"/LibraryMgt/vendors/counter-up/jquery.waypoints.min.js\"></script>\r\n");
      out.write("        <script src=\"/LibraryMgt/vendors/counter-up/jquery.counterup.js\"></script>\r\n");
      out.write("        <script src=\"/LibraryMgt/js/mail-script.js\"></script>\r\n");
      out.write("        <script src=\"/LibraryMgt/js/theme.js\"></script> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
